### ISSUE TITLE
Privacy and Read-only settings for threads is unclear and buggy.

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth-oss#159]

**Comment by raykyri** [comment]
On the design side I'll take a look. But in the meantime this logic in routes/editThread.ts seems worth taking another look at, if we want to change it to be more straightforward:

```
55:    if (privacy) thread.private = false;
```

**Comment by drewstone** [comment]
It seems because we have made some spec decisions such as "Not turning public threads private", these situations becomoe hairy.

Even though this doesn’t seem accurately captured, we may have conflicting design decisions around private threads

Likely will want to think through more about what decisions we will take and how readable/reviewable/usable they will be to other developers.

**Comment by drewstone** [comment]
In situations like these, we need more comments in the code in order to help us understand the intention @zakhap
