### ISSUE TITLE
Create "more" and "home" buttons on the community switcher; make community switcher always visible

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth-oss#180]
- [x] Replace the thinking face emoji with a xl-sized home icon. Clicking the home icon should take you directly home to the root page of Commonwealth ('/')
- [x] Add a 'more' button at the bottom of the community switcher, after all chains and communities. It should be styled and componentized similarly as the chain and community tiles (use SCSS variables where possible), except it should have horizontal ellipses (...) as the icon. Clicking this icon should open the community menu.
- [x] Remove the home menu option from the community menu
- [x] With these changes in place, we can make the community switcher sidebar always visible on all pages, even when logged-out. (Right now it doesn't show on the homepage when logged out.) When this is the case, the More option should be hidden, so just the home icon is visible on the top left.

**Comment by dillchen** [comment]
#214 does address this. Question, will we change the home icon to the CW logo or leave as is (with additional styling changes).
