### ISSUE TITLE
Replace animated placeholder with construct-ui spinner for Proposals and Council pages

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth-oss#185]
Right now we use this animated placeholder:

![image](https://user-images.githubusercontent.com/1273926/81144132-46f2c300-8f28-11ea-9c7f-f34e1aa5433b.png)

We should replace this placeholder with a construct-ui spinner, like on the discussions page. 

Then we should also make it so the spinner says when the chain is loading, by setting a message property (e.g. "Waiting for chain"): https://vrimar.github.io/construct-ui/#/components/spinner

**Comment by gdjohnson** [comment]
Closing; see PR #193.
