### ISSUE TITLE
Add notifications component & user menu component to home page

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth-oss#186]
These two components need to be shown on the homepage in the top right, if the user is logged in:

![image](https://user-images.githubusercontent.com/1273926/81144431-e4e68d80-8f28-11ea-968c-e383e341aaec.png)

Otherwise, we should show a Login button in the top right (this is also in the Header right now).

Otherwise the homepage is empty and disorienting:

![image](https://user-images.githubusercontent.com/1273926/81144474-faf44e00-8f28-11ea-850b-09b442714eb3.png)

It might be necessary to do some refactoring to make the components easily reusable...or it might not.

**Comment by gdjohnson** [comment]
PR #195 created, pending review.
