### ISSUE TITLE
Use should be able to join a community from within it

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth-oss#238]
## Description
AFAICT (@raykyri or @zakhap feel free to correct me) there isn't a way to join communities once inside them; that functionality only exists from the homepage.

To my eyes, the settings dropdown in header is the best spot:
![image](https://user-images.githubusercontent.com/22281010/82694099-a9d6a080-9c30-11ea-944e-75fec5216434.png)

Alternatively, we could include it here:
![image](https://user-images.githubusercontent.com/22281010/82694156-c1ae2480-9c30-11ea-9cb7-40aa1caf83d5.png)

## *Who* is the bug affecting?
Users who want to join a new community, but can't figure out how to.

**Comment by raykyri** [comment]
I have a ticket open to look at the design side of this - let's hold on this for now because I think the header design will still change somewhat.

**Comment by raykyri** [comment]
Closing this in favor of #106.
