### ISSUE TITLE
Clicking "Show more" on the discussion page should not append ?lookback= to the URL repeatedly

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth-oss#34]
Currently it naively appends to the URL resulting in this:

![image](https://user-images.githubusercontent.com/1273926/80176815-a5c24f00-85ae-11ea-8a97-fcf62e47e298.png)

We can remove the lookback param altogether (both writing it to the URL, and anywhere we read it from the URL.)

**Comment by gdjohnson** [comment]
Will this be rendered obsolete given the infinite scroll feature?

**Comment by raykyri** [comment]
Seems so, we can deprecate this in favor of the infinite scroll task.
