### ISSUE TITLE
Non-featured tags should be sorted by name wherever they are displayed

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth-oss#45]
![image](https://user-images.githubusercontent.com/1273926/80179671-ed98a480-85b5-11ea-8bdd-06db71e1e6f4.png)

**Comment by zakhap** [comment]
Current Status: 
- Feature Tags are in Drag Order
- Tags on Discussion Rows are alphabetical (updated)
- "Other Tags"/Non-Feature tags on Tag Page are in order of most used, and where there are multiple tags with the same count, order alphabetically.

Is this the behavior we want?
