### ISSUE TITLE
Show unread threads/comments as a notification pip in the CommunitySwitcher sidebar

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth-oss#95]
A simple dot in the top right of each community or chain icon (similar to Discord's design) seems sufficient. We can also avoid showing unread count for now; having the homepage serve as the universal inbox may turn out to be enough.

**Comment by gdjohnson** [comment]
Assuming this is on Construct-UI branch, and I should branch from there? On it!

**Comment by raykyri** [comment]
Yep - off construct-ui in the community switcher part of the sidebar, there should be user icons showing on the bottom right of community. Top right would be a good place for notification pips. Also open to other ideas on how to show user membership in communities!
